<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="lidar_radius" value="0.05" />
    <xacro:property name="lidar_length" value="0.02" />

    <link name="base_scan">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}" />
            </geometry>
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}" />
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="0.1" r="${2*lidar_radius}" h="${2*lidar_length}"
                                xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="base_scan_joint" type="fixed">
        <parent link="base_link" />
        <child link="base_scan" />
        <origin xyz="0 0 ${base_height+0.05}" rpy="0 0 3.14" />
    </joint>

    
    <gazebo reference="base_scan">
        <sensor name="lidar" type="ray">
        <pose>0.215 0 0.215 0 0 0</pose>
        <always_on>true</always_on>
        <visualize>false</visualize>
        <update_rate>5</update_rate>
        <ray>
            <scan>
                <horizontal>
                    <samples>720</samples>
                    <resolution>1.00000</resolution>
                    <min_angle>0.000000</min_angle>
                    <max_angle>6.280000</max_angle>
                </horizontal>
            </scan>
            <range>
                <min>0.120000</min>
                <max>3.5</max>
                <resolution>0.015000</resolution>
            </range>
            <noise>
                <type>gaussian</type>
                <mean>0.0</mean>
                <stddev>0.01</stddev>
            </noise>
        </ray>
        <plugin name="scan" filename="libgazebo_ros_ray_sensor.so">
            <ros>
                <remapping>~/out:=scan</remapping>
            </ros>
            <output_type>sensor_msgs/LaserScan</output_type>
            <frame_name>base_scan</frame_name>
        </plugin>
        </sensor>
    </gazebo>

</robot>