<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.26" />
    <xacro:property name="base_width" value="0.15" />
    <xacro:property name="base_height" value="0.08" />
    <xacro:property name="wheel_radius" value="0.04" />
    <xacro:property name="wheel_length" value="0.02" />

    <link name="base_footprint" />
    <!-- collision and inertia box close to floor for lateral movements -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="yellow" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 0.0" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="4.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}"
                           xyz="0 0 0.0" rpy="0 0 0" />
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                    <!--<mesh filename="package://my_robot_description/meshes/left_tire.stl" scale="0.001 0.001 0.001"/>-->
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>
            <xacro:cylinder_inertia m="0.2" r="${2*wheel_radius}" h="${2*wheel_length}" 
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="lower_right" />
    <xacro:wheel_link prefix="lower_left" />
    <xacro:wheel_link prefix="upper_right" />
    <xacro:wheel_link prefix="upper_left" />

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="lower_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="lower_right_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="lower_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="lower_left_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="upper_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="upper_right_wheel_link" />
        <origin xyz="${base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="upper_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="upper_left_wheel_link" />
        <origin xyz="${base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>


</robot>